### ISSUE TITLE
user_loader is None

### ISSUE THREAD

**Issue by magwas** [maxcountryman/flask-login#212]
in my main, I do

    @login_manager.user_loader
    def load_user(userid):
        return User.get(userid)

and I have all the route definitions _ater_ it, in the same python file.
And I still get the following error:

      File "src/pdoauth/main.py", line 37, in showUser
        return do_show_user(userid)
      File "/project/mag/pdoauth/src/pdoauth/auth.py", line 123, in do_show_user
        allowed, targetuser = isAllowedToGetUser(userid)
      File "/project/mag/pdoauth/src/pdoauth/auth.py", line 58, in isAllowedToGetUser
        if current_user.is_authenticated():
      File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
        return getattr(self._get_current_object(), name)
      File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 297, in _get_current_object
        return self.__local()
      File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 46, in <lambda>
        current_user = LocalProxy(lambda: _get_user())
      File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 794, in _get_user
        current_app.login_manager._load_user()
      File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 363, in _load_user
        return self.reload_user()
      File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 325, in reload_user
        user = self.user_callback(user_id)
    TypeError: 'NoneType' object is not callable
    
I get the above error when running the application. I never get the error in unit tests, when I am using test_client.

to reproduce the bug, do the following:

     git clone https://github.com/edemo/PDOauth.git
     cd PDOauth/
     git checkout 6ae96e4fb345ce3c42474c94577a07395d4086ad
     make

You can see the output at https://travis-ci.org/edemo/PDOauth/builds/61745917

**Comment by magwas** [comment]
The problem seems to be related to the fact that application initialization was done in a different module (app), and it was imported twice, with different module paths. the below diff to my application have resolved the problem.
I leave it to your judgement whether it is a bug in flask-login, or not.

    diff --git a/src/pdoauth/main.py b/src/pdoauth/main.py
    index 51df1ca..8db58d5 100644
    --- a/src/pdoauth/main.py
    +++ b/src/pdoauth/main.py
    @@ -1,10 +1,9 @@
    -from app import app
    +from app import app, login_manager
     from pdoauth.AuthProvider import AuthProvider
     from pdoauth.auth import do_login, do_registration, do_get_by_email,\
         do_add_assurance, do_show_user, do_verify_email, error_response
     from flask_login import login_required
     from flask.helpers import send_from_directory
-    from pdoauth.app import login_manager
     from pdoauth.models.User import User
     import os

**Comment by CrowderSoup** [comment]
I'm experiencing the same issue. Everything seemed to be working until I upgraded my projects dependencies this morning and now I can't figure out what could be going on.

The error I'm getting is TypeError: 'NoneType' object is not callable. Here is the full stack trace:
```
Traceback (most recent call last):
File "C:\Users\acrowder\venv\lib\site-packages\flask\app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\acrowder\venv\lib\site-packages\flask\app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "C:\Users\acrowder\venv\lib\site-packages\flask\app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\acrowder\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
raise value
File "C:\Users\acrowder\venv\lib\site-packages\flask\app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\acrowder\venv\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\acrowder\venv\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\acrowder\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
raise value
File "C:\Users\acrowder\venv\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\acrowder\venv\lib\site-packages\flask\app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Code\crowdcontrol\app\site\views.py", line 52, in page
return render_template(template_path, page=the_page, menu=menu)
File "C:\Users\acrowder\venv\lib\site-packages\flask\templating.py", line 126, in render_template
ctx.app.update_template_context(context)
File "C:\Users\acrowder\venv\lib\site-packages\flask\app.py", line 716, in update_template_context
context.update(func())
File "C:\Users\acrowder\venv\lib\site-packages\flask_login.py", line 825, in _user_context_processor
return dict(current_user=_get_user())
File "C:\Users\acrowder\venv\lib\site-packages\flask_login.py", line 794, in _get_user
current_app.login_manager._load_user()
File "C:\Users\acrowder\venv\lib\site-packages\flask_login.py", line 363, in _load_user
return self.reload_user()
File "C:\Users\acrowder\venv\lib\site-packages\flask_login.py", line 325, in reload_user
user = self.user_callback(user_id)
TypeError: 'NoneType' object is not callable
```
Here's my init.py for my app:
```
import os
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.mail import Mail
from flask.ext.moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from config import config
from app.jinja_filters import format_datetime

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()

login_manager = LoginManager()

def create_app(config_name):
    the_app = Flask(__name__)
    the_app.config.from_object(config[config_name])
    config[config_name].init_app(the_app)

    bootstrap.init_app(the_app)
    mail.init_app(the_app)
    moment.init_app(the_app)
    db.init_app(the_app)

    # Let's set up our login handlers
    import app.login_handlers
    login_manager.session_protection = 'strong'
    login_manager.login_view = 'auth.login'
    login_manager.init_app(the_app)

    the_app.jinja_env.filters['datetime'] = format_datetime

    from app.site import site as site_blueprint
    the_app.register_blueprint(site_blueprint)

    from app.blog import blog as blog_blueprint
    the_app.register_blueprint(blog_blueprint)

    from app.admin import admin as admin_blueprint
    the_app.register_blueprint(admin_blueprint, url_prefix="/admin")

    from app.auth import auth as auth_blueprint
    the_app.register_blueprint(auth_blueprint, url_prefix="/auth")

    return the_app


app = create_app(os.getenv('FLASK_CONFIG') or 'default')

if __name__ == "__main__":
    app.run()
```
And here's my login_handlers.py file:
```
from app import login_manager
from app.models import User


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
```
I've put in breakpoint in flask_login.py on line 216, and it seems to be called twice. But I can't figure out from where.

**Comment by gaulinmp** [comment]
I'm also having this problem. My stack trace is roughly the same as already submitted, but I have verified (with print statements) that User is being loaded on the models side, but None is received on the user_loader side:

```python
def get_by_id(user_id):
    uuser = User.search(user_id=user_id)
    print("get_by_id: {}".format(uuser))
    return uuser
```
>>> User(0:admin)

```python
@login_manager.user_loader
def load_user(user_id):
    uuser = User.get_by_id(int(user_id))
    print("load_user: {}".format(uuser))
    return uuser
```
>>> None

**Comment by AhnSeongHyun** [comment]
this is bug??

**Comment by maxcountryman** [comment]
Please update to `0.3.0`.
