### ISSUE TITLE
importing UserMixin

### ISSUE THREAD

**Issue by ruttydm** [maxcountryman/flask-login#346]
I have a problem with importing the UserMixin. (I'm on the most recent python version)

This are my import lines:

```
from flask import Flask,render_template,redirect,request,url_for,session,Response,UserMixin
from flask_login import LoginManager, current_user, login_user, login_required, logout_user
```

and this is the error i got: 

```
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from main import *
  File "/home/ruttydm/Dropbox/CODING/python/sw/main.py", line 1, in <module>
    from flask import Flask,render_template,redirect,request,url_for,session,Response,UserMixin
ImportError: cannot import name 'UserMixin'
```

Beside this I am also struggling to get flask-login working.
Please view my stackoverflow post: [http://stackoverflow.com/questions/43033461/flask-login-does-not-login](url)

**Comment by davidism** [comment]
`from flask_login import UserMixin`

**Comment by Reshaniresh** [comment]
I also getting the same error??and i even tried the below code .but still facing the same

****

```
from flask import Flask, render_template, request, session,abort

from flask_login import UserMixin

from flask_sqlalchemy import SQLAlchemy
```

```
 from flask_login import UserMixin
ImportError: cannot import name 'UserMixin' from 'flask_login'
```
