### ISSUE TITLE
login_user unable to set session cookie - how to debug?

### ISSUE THREAD

**Issue by gsidhu** [maxcountryman/flask-login#497]
**Describe the bug**
The user's details are collected via Google OAuth and stored in a db. The data reflects perfectly in the db, however, in the callback function, when the `user` object is passed to the `login_user` function, I get the following error –

```python
Traceback (most recent call last):
  File "/home/user/otpd/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/otpd/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/otpd/venv/lib/python3.6/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/home/user/otpd/venv/lib/python3.6/site-packages/flask/app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/home/user/otpd/venv/lib/python3.6/site-packages/flask/sessions.py", line 387, in save_session
    samesite=samesite,
  File "/home/user/otpd/venv/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 481, in set_cookie
    samesite=samesite,
  File "/home/user/otpd/venv/lib/python3.6/site-packages/werkzeug/http.py", line 1163, in dump_cookie
    buf = [key + b"=" + _cookie_quote(value)]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'bytes'
```

**Expected behavior**
Ideally, the user should be logged in. :)

**Desktop:**
 - OS: Mac OS
 - Browser Firefox, Chrome
 - Version: 75, 81

**Additional context**
1. I followed [this tutorial on Real Python](https://realpython.com/flask-google-login/#creating-your-own-web-application) to set the code up for my website. [codebase here](https://github.com/realpython/materials/blob/master/flask-google-login/user.py) I modified the code by breaking it into a blueprint and using application factory method to launch.
2. The code runs on a remote server using Gunicorn.
3. When I run the code locally, there are no issues. The issue only crops up on the remote server.

Any suggestions on how to debug this?

Thanks!

**Comment by gsidhu** [comment]
Fixed. I had set an invalid SESSION_COOKIE_NAME in my config file. Changed that and everything works.

For the adventurers who end up on this issue in the future: Make sure you are setting up session environment variables correctly! You need an app secret and a session cookie name for Flask Sessions to run.

**Comment by xiayulu** [comment]
This helps me a lot, Thanks
