### ISSUE TITLE
Werkzeug clients share current_user??  That's not right.

### ISSUE THREAD

**Issue by andyDoucette** [maxcountryman/flask-login#721]
# Objective
I am using the werkzeug.test.Client to run tests on my flask application without having to run a server.

I would like to test that logged in users can access certain resources and not-logged in users cannot.

# Procedure
I make a client called test_client with `test_client=Client(app)` and then log it in using the flask_security_too `/login` route.

I make another client called "mal_client" with `mal_client=Client(app)`, and don't log it in.  When I use mal_client to access a route protected with `@login_required`, flask_login lets it access the route when it shouldn't (because that client is not logged in.).

I can verify that there are no request headers other than `Host` set on mal's request (no cookies from test_client being sent), so I am not sure why the request is getting through.

# Reproducing
I made a super-simple flask app that demonstrates the issue. Since it's difficult to pdb into a @login_required decorator, I instead made a route called `is_logged_in` that just returns current_user.is_authenticated (what @login_required is supposed to reference anyway). That shows that mal_client is somehow logged in even when it's not sending any session cookies.

Most of the demonstration app is adapted from this [Flask-Security-Too Quick Start](https://flask-security-too.readthedocs.io/en/stable/quickstart.html#basic-sqlalchemy-application-with-session).

`is_logged_in.py` is my is_logged_in route, and `logging_hooks.py` is what I use to inspect the headers received and sent. Other than that, most of the main logic is in `user_test_app.py`, which is the "main" file that is run with `python3 ./user_test_app.py`

## user_test_app.py
``` python
#!/usr/bin/python3

from flask_security import current_user, auth_required, hash_password
from flask import render_template_string
from database import db_session, init_db
from is_logged_in import is_logged_in
from werkzeug.test import Client
from logging_hooks import *
from app import app
import os

def run_tests(app):
    
    app.config['WTF_CSRF_ENABLED'] = False
    
    test_client=login_test_client()
    
    mal=assure_mal_not_logged_in()
    
def assure_mal_not_logged_in():
    mal_client=Client(app)
    
    response=mal_client.get('/is_logged_in')
    assert response.status_code == 200
    
    assert response.json==False
    
    return mal_client

    
def login_test_client():
    test_client=Client(app)
    
    result=test_client.post('/login', json={
        'next': '/', 
        'email': 'test@me.com',
        'password' : 'password',
        'remember': 'y', 
        'submit': 'Login',
    })
    assert result.status_code == 200
    
    response=test_client.get('/is_logged_in')
    assert response.status_code == 200
    
    assert response.json==True
    
    return test_client

if __name__ == '__main__':
    with app.app_context():
        # Create a user to test with
        init_db()
        if not app.security.datastore.find_user(email="test@me.com"):
            app.security.datastore.create_user(email="test@me.com", password=hash_password("password"))
        db_session.commit()
        
        run_tests(app)
        
        #app.run(host='0.0.0.0', port=9000)
```

## Results
When I run this, I get this:
    
```
[2022-12-10 07:06:38,644] DEBUG in logging_hooks: 
↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓ GET request from None for http://localhost/is_logged_in

Request Headers: 
Host: localhost

Request Body: 
b''

======
[2022-12-10 07:06:38,644] DEBUG in logging_hooks: 
======
Response Summary:
<Response 5 bytes [200 OK]>

Response Headers:
Content-Type: application/json
Content-Length: 5

Response Body: 
true

↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑
Traceback (most recent call last):
  File "/app/user_test_app/./user_test_app.py", line 58, in <module>
    run_tests(app)
  File "/app/user_test_app/./user_test_app.py", line 18, in run_tests
    mal=assure_mal_not_logged_in()
  File "/app/user_test_app/./user_test_app.py", line 26, in assure_mal_not_logged_in
    assert response.json==False
AssertionError

```

In other words, mal is logged in when he shouldn't be.  Note how my logging shows that the request was made with just the Host header (no session), yet the response was true (aka current_user.is_authenticated was true).

## is_logged_in.py
``` python
from flask_security import current_user, login_required
from app import app
import flask

@app.route('/is_logged_in')
def is_logged_in():

    is_logged_in=current_user.is_authenticated
    
    return flask.jsonify(is_logged_in)

```

## app.py
``` python
#!/usr/bin/python3

import os

from flask import Flask
from flask_security import Security, SQLAlchemySessionUserDatastore
from database import db_session
from models import User, Role

# Create app
app = Flask(__name__)
app.config['DEBUG'] = True

# Generate a nice key using secrets.token_urlsafe()
app.config['SECRET_KEY'] = os.environ.get("SECRET_KEY", 'pf9Wkove4IKEAXvy-cQkeDPhv9Cb3Ag-wyJILbq_dFw')
# Bcrypt is set as default SECURITY_PASSWORD_HASH, which requires a salt
# Generate a good salt using: secrets.SystemRandom().getrandbits(128)
app.config['SECURITY_PASSWORD_SALT'] = os.environ.get("SECURITY_PASSWORD_SALT", '146585145368132386173505678016728509634')

# Setup Flask-Security
user_datastore = SQLAlchemySessionUserDatastore(db_session, User, Role)
app.security = Security(app, user_datastore)
```
## database.py
``` python
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session, sessionmaker
from sqlalchemy.ext.declarative import declarative_base

engine = create_engine('sqlite:////tmp/test.db')
db_session = scoped_session(sessionmaker(autocommit=False,
                                         autoflush=False,
                                         bind=engine))
Base = declarative_base()
Base.query = db_session.query_property()

def init_db():
    # import all modules here that might define models so that
    # they will be registered properly on the metadata.  Otherwise
    # you will have to import them first before calling init_db()
    import models
    Base.metadata.create_all(bind=engine)
```    

## models.py
``` python
from database import Base
from flask_security import UserMixin, RoleMixin
from sqlalchemy import create_engine
from sqlalchemy.orm import relationship, backref
from sqlalchemy import Boolean, DateTime, Column, Integer, \
                    String, ForeignKey, UnicodeText

class RolesUsers(Base):
    __tablename__ = 'roles_users'
    id = Column(Integer(), primary_key=True)
    user_id = Column('user_id', Integer(), ForeignKey('user.id'))
    role_id = Column('role_id', Integer(), ForeignKey('role.id'))

class Role(Base, RoleMixin):
    __tablename__ = 'role'
    id = Column(Integer(), primary_key=True)
    name = Column(String(80), unique=True)
    description = Column(String(255))
    permissions = Column(UnicodeText)

class User(Base, UserMixin):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    email = Column(String(255), unique=True)
    username = Column(String(255), unique=True, nullable=True)
    password = Column(String(255), nullable=False)
    last_login_at = Column(DateTime())
    current_login_at = Column(DateTime())
    last_login_ip = Column(String(100))
    current_login_ip = Column(String(100))
    login_count = Column(Integer)
    active = Column(Boolean())
    fs_uniquifier = Column(String(255), unique=True, nullable=False)
    confirmed_at = Column(DateTime())
    roles = relationship('Role', secondary='roles_users',
                         backref=backref('users', lazy='dynamic'))
```

## logging_hooks.py
``` python
from app import app
from flask import request

@app.before_request
def log_request_info():
    message=f'''
↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓ {request.method} request from {request.remote_addr} for {request.url}

Request Headers: 
{request.headers}Request Body: 
{request.get_data()}

======'''

    app.logger.debug(message)

@app.after_request
def log_response_info(response):
    message=f'''
======
Response Summary:
{str(response)}

Response Headers:
{str(response.headers)}'''
    #Only log details for responses that aren't pass-through (static files are pass-through, for example):
    try:
        if not response.direct_passthrough:
            message +=f'Response Body: \n{response.get_data().decode("utf-8")}'
    except: pass
    
    message+='\n↑↑\n↑↑↑↑↑↑↑↑↑↑↑↑↑↑'
    
    app.logger.debug(message)

    return response

```

# Questions
1. What's the root cause and how can we fix it?  I'm pretty sure that two different clients should not be affecting each-other this way.

**Comment by andyDoucette** [comment]
# Update: 

It seems that the behavior doesn't seem to be only with the use of two test clients.  Just clearing the cookies on one test client after login makes it still act like it's logged in.  Clearing the cookies should definitely log any client out, right?

## An updated user_test_app.py with just one client:
``` python
#!/usr/bin/python3

from flask_security import current_user, auth_required, hash_password
from flask import render_template_string
from werkzeug.test import _TestCookieJar
from database import db_session, init_db
from is_logged_in import is_logged_in
from werkzeug.test import Client
from logging_hooks import *
from app import app
import os

test_client=Client(app)

def run_tests(app):
    global test_client
    
    app.config['WTF_CSRF_ENABLED'] = False
    assert is_logged_in()==False
    
    test_client=login_client(test_client)
    assert is_logged_in()==True
    
    #Clear the cookies on the client:
    test_client.cookie_jar=_TestCookieJar()
    #WARNING: That should log the client out, but it doesnt:
    assert is_logged_in()==False
    
def is_logged_in():
    
    response=test_client.get('/is_logged_in')
    assert response.status_code == 200
    
    return response.json

    
def login_client(client):
    result=client.post('/login', json={
        'next': '/', 
        'email': 'test@me.com',
        'password' : 'password',
        'remember': 'y', 
        'submit': 'Login',
    })
    assert result.status_code == 200
    
    response=client.get('/is_logged_in')
    assert response.status_code == 200
    
    assert response.json==True
    
    return client

if __name__ == '__main__':
    with app.app_context():
        # Create a user to test with
        init_db()
        if not app.security.datastore.find_user(email="test@me.com"):
            app.security.datastore.create_user(email="test@me.com", password=hash_password("password"))
        db_session.commit()
        
        run_tests(app)
```

## When run:
```
...
Traceback (most recent call last):
  File "/app/user_test_app/./user_test_app.py", line 62, in <module>
    run_tests(app)
  File "/app/user_test_app/./user_test_app.py", line 27, in run_tests
    assert is_logged_in()==False
AssertionError
```

**Comment by couchounou** [comment]
I have also a sharing of "current_user" of  ALL logged users when upgrading from flask 0.6.1 to 0.6.2...

**Comment by albertca** [comment]
I have the same issue, it seems Flask-Login is broken in Flask 2.2

**Comment by raimonesteve** [comment]
> I have the same issue, it seems Flask-Login is broken in Flask 2.2

Versions:

```
Werkzeug==2.2.2
Flask==2.2.2
Flask-Login==0.6.2
gunicorn==20.1.0
```

We detect that **current_user** is not reload between workers.

Maybe is related to '_request_ctx_stack' is deprecated and will be removed in Flask 2.3. 

Since https://github.com/maxcountryman/flask-login/commit/359fb004f153635952a7d32ded1bbd6d74ec2561 current_user is from g._login_user. But, In case you run your flask app with differents workers, in some cases "_get_user" is anonymous and other cases,  is the user.

Gunicorn command:

```
gunicorn -w 4 -b 0.0.0.0:8020 --timeout 3600 --max-requests 10000 --disable-redirect-access-to-syslog --capture-output --error-logfile - extranet:app
```

At the moment,  down versions to solve:

```
Werkzeug==2.1.2
Flask==2.1.3
Flask-Login==0.6.1
```

**Comment by davidism** [comment]
Don't put `with app.app_context()` around calls to the test client. Flask will automatically push an app context and request context during each request. Pushing one manually tells Flask not to push one itself, which makes it reuse the same context across requests. Only push an app context if your are testing (or setting up) something outside of a request.
